server:
  port: 9095

spring:
  application:
    name: NOTIFICATION-SERVICE
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ee33c71ae07b86
    password: 156d48fd85e95b
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: identity-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/