server:
  port: 9095

spring:
  application:
    name: NOTIFICATION-SERVICE




  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: identity-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/