spring:
  application:
    name: IDENTITY-SERVICE
  kafka:
    bootstrap-servers: localhost:9092

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/


server:
  port: 9898

kafka:
  topic:
    user-info: user-info