server:
  port: 9094

spring:
  application:
    name: transportation-service

  datasource:
    url: jdbc:mysql://localhost:3306/transport
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: transporter-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/